spring:
  kafka:
    streams:
      application-id: "kafka-streams"
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: my-stream-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false


main:
  topic:
    consumer: test_topic
    producer: test_producer